In [2]:
import numpy as np

In [3]:
A = np.array([[3, 1, -2],
              [0, 5, 3]])

B = np.array([[4], [3], [5]])
C = np.array([[2, -1], 
              [0, 3]])


In [6]:
# Manual matrix multiplication

# Matrix x Vector, results in a vector with the same depth as the matrix
AB = np.array([[3 * 4 + 1 * 3 + -2 * 5], [0 * 4 + 5 * 3 + 3 * 5]])
# Matrix x Matrix
CA = np.array([[2 * 3 - 1 * 0, 2 * 1 - 1 * 5, 2 * (-2) - 1 * 3],
               [0 * 3 + 3 * 0, 0 * 1 + 3 * 5, 0 * (-2) + 3 * 3]])
AB

array([[ 5],
       [30]])

In [7]:
CA

array([[ 6, -3, -7],
       [ 0, 15,  9]])

In [8]:
# Numpy matrix multiplication
np.dot(A, B)

array([[ 5],
       [30]])

In [9]:
A @ B

array([[ 5],
       [30]])

In [11]:
At = A.transpose()
At

array([[ 3,  0],
       [ 1,  5],
       [-2,  3]])