## Tehtävä 1

In [7]:
import numpy as np

A0 = np.array([[3], [2], [5]])
W1 = np.array([[1.1, -1.3, 1.5], [0.1, 2.0, 1.7]])
W2 = np.array([[2.0, -1.2]])

A1 = np.dot(W1, A0)
A2 = np.dot(W2, A1)

In [8]:
print("Matriisi A1:")
print(A1)
print("Matriisi A2:")
print(A2)

Matriisi A1:
[[ 8.2]
 [12.8]]
Matriisi A2:
[[1.04]]


## Tehtävä 2

In [12]:
def relu(x):
    return np.maximum(x, 0)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

A1 = relu(np.dot(W1, A0))
A2 = sigmoid(np.dot(W2, A1))

In [13]:
print("Matriisi A1:")
print(A1)
print("Matriisi A2:")
print(A2)

Matriisi A1:
[[ 8.2]
 [12.8]]
Matriisi A2:
[[0.73885001]]


## Tehtävä 3

In [22]:
vector_x = np.arange(1, 11).reshape(-1, 1) # luo sarjan 1-10 ja muuttaa sen vektoriksi
vector_y = np.array([[14], [12], [34], [24], [43], [38], [41], [57], [55], [50]])

print("Vektori x:")
print(vector_x)
print("Vektori y:")
print(vector_y)

Vektori x:
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
Vektori y:
[[14]
 [12]
 [34]
 [24]
 [43]
 [38]
 [41]
 [57]
 [55]
 [50]]


In [54]:
ones = np.ones(10)
X = np.vstack([ones, vector_x.reshape(1, -1)])
X = X.T

print("Matriisi X:")
print(X)
print(vector_y.reshape(1, -1))

Matriisi X:
[[ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 1.  8.]
 [ 1.  9.]
 [ 1. 10.]]
[[14 12 34 24 43 38 41 57 55 50]]


In [58]:
M = np.linalg.inv(X.T @ X) @ X.T @ vector_y

print("Matriisi M:")
print(M)

Matriisi M:
[[10.6       ]
 [ 4.76363636]]


In [66]:
import matplotlib.pyplot as plt

xx = np.linspace(1, 10, 1000)
XX = np.column_stack((np.ones_like(xx), xx))
yy = XX.dot(M)
plt.plot(vector_x, vector_y, 'o')
plt.plot(xx, yy)


ValueError: shapes (1001,) and (2,1) not aligned: 1001 (dim 0) != 2 (dim 0)